### ISSUE TITLE
HDIV Support For Mustache/AngularJS Integration

### ISSUE THREAD

**Issue by krish264u** [hdiv/hdiv#69]
Hi,

I'm currently working on my new Spring MVC web app and trying to incorporate new web architecture in which avoiding UI processing(JSP/JSF/JSTL etc) at the server and controllers will act purely REST api's to serve the json page data model. At client, I'm planning to use Mustache JS/AngularJS to parse json data response and construct full html in browser. 

Interaction between browser and webapp is pure ajax calls with json data format in request and response.

I have major issue now with HDIV in this environment as currently supports only server side UI templating frameworks such as JSP+JSTL, JSF, ThemeLeaf using Struts/SpringMVC in which it is able to control all the data into its state.

I would need help/direction from you to extend HDIV to pure json data based model exchange between client and server so that we can adopt pure client side frameworks such as mustache or AngularJS etc.

Request to provide short and long term plans to achieve this model.

Any help appreciated!

Thank you.

Regards,
Krishnaraj

**Comment by robertovelasco** [comment]
Hi Krishnaraj,

For client-mvc scenarios such as AngularJS Spring-Hateoas approach fits well with HDIV. Actually, HDIV has a module for that integration: https://github.com/hdiv/hdiv/tree/hdiv-hateoas

It’s not totally finished yet but the integration of URL resources works (see ResourceRequestDataValueProcessor) but it’s not finished the support for forms. When we started this module this data format for forms was not finished or defined, and that’s why we did not continue this work.

We think it could be possible a very integrated solution with HDIV following Hypermedia and HATEOAS approach for client-mvc apps or also for native mobile apps. In other words, within REST Hypermedia approach all URLs or forms, excepting the first URL, are created in the server side, in a similar way of traditional server side MVC web technologies.

Please take a look to this module (hdiv-hateoas) and we can support you if you have any doubts.

We have scheduled support for this scenarios (REST interactions) in our future roadmap (probably for 2015) because it makes possible to use HDIV features in client MVC scenarios as well as mobile native web applications scenarios that use REST services.

Roberto Velasco (HDIV team)

**Comment by krish264u** [comment]
Thanks Roberto Velasco. Appreciate quick reply. I tried hdiv-hateoas but didnt helped much. I may be doing something wrong but continue to investigate.

I'm not sure hdiv-hateoas would fix the issue completely as we know, all of the json response need not be added to hdiv state as json is mix of form elements and other info only tags such as image path etc,

Here is the most likely scenario in this architecture, during page load, UI makes first ajax call to get pagemodel of the page requested by customer. Server responds with json response and it contains form details (all form fields, action, method type etc.) and other such as image path etc.

When customer clicks on submit, ui will make form submit in ajax way and when request is submitted, hdiv should process this form submit and controller will provide next page model json response. In summary, the form submit in regular html form submit and response is json. This handshake works only if hdiv knows all form elements and in this case, we need to manually add these form fields to hdiv state.

In quick fix, I'm trying to extract the form field elements from my page model and adding to hdiv state before return in controller. UI Mustache/JS code gets these form elements in json and constructs the html form.

I could add the form action url to hdiv stage using HDIVUtil and FormUrlProcessor(see below code)  but unable to add the form fields to hdiv state. Due to this, the next ajax call is partially successful but fail with invalid parameter as the param is not in hdiv state.

Also, action url with param added are automatically getting classified as non-editable and any change to var. is not allowed and it would fail.

FormUrlProcessor formUrlProcessor = HDIVUtil.getFormUrlProcessor(context);

String formurl= "http://localhost:8080/myapp/update";
formurl = linkUrlProcessor.processUrl(request, formurl);

To add the form fields to hdiv state, I tried below but not successful.

IDataComposer dataComposer = (IDataComposer) request.getAttribute(HDIVUtil.DATACOMPOSER_REQUEST_KEY);

dataComposer.beginRequest("GET","http://localhost:8080/myapp/update");

dataComposer.compose("addressLine1", "", true, "text");
HDIVUtil.setDataComposer(dataComposer, request);
dataComposer.endRequest();

I think my issue would be solved if I could find way to manually add all the form fields elements (IParameter) to hdiv state. I'm not sure this is right but looking at options available, I see this best workaround to this new architecture.

Appreciate if you could help provide some code sample.

Regards,
Krishnaraj

**Comment by gillarramendi** [comment]
In your approach you might use 'composeFormField' method to compose form fields:
```java
dataComposer.composeFormField(name, value, true, type); 
```
Do this after FormUrlProcessor.processUrl call.

This is the order for form field composition:
1. FormUrlProcessor.processUrl(..) with the action url
2. dataComposer.composeFormField(..) for every form field
3. dataComposer.endRequest(); to obtain the new state id and add it to the form as a hidden field.

**Comment by krish264u** [comment]
Thank you. We are able to fix this issue and working great!!!
