### ISSUE TITLE
HDIV 3.0.0 execution strategies 

### ISSUE THREAD

**Issue by gopus** [hdiv/hdiv#89]
As per the documentation now HDIV 3.0.0 only supports memory strategy.  what happened to "cipher strategy"?  why were the other two strategies (Hash and Cipher) removed? can someone shed some light on this.  Thanks

**Comment by robertovelasco** [comment]
The cipher and hash strategies have not been maintained in at least the last 5-6 years releases. In other words, in practice we have been only maintaining one strategy (memory) and in order to assure the security and the quality of the solution we have just released memory strategy support in the lastest Hdiv version.

In advance, legacy strategies such as hash and cipher, as well as more advanced strategies (that we call high scalability) will be supported only in the Enterprise Edition of Hdiv.

Roberto

**Comment by gopus** [comment]
Thanks for the info Roberto.
